services:
  backend:
    build:
      context: ./back
    env_file:
      - .env
    ports:
      - "4000:3000"
    command: npm run start:prod
    volumes:
      - ./back:/app
    working_dir: /app

  frontend:
    build:
      context: ./front
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: npm run start
    volumes:
      - ./front:/app
    working_dir: /app

